# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 143d3db17186de553c9c4c252d00c0e13f6b722eed7e7c50e0695761da66225902091b5a5f181b368cdaf664aa6a522262dac1fd530f414b755f32a3aaf82b37

test:
  secret_key_base: 2a765aa22684070d2d970d5ed329e8d6e0da21d723ca7e5f622e7815f7130f8ec7e4800538c367f3e57afa731319570e35b6361bf3576c097e97be8fff704a62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
